# Generated by Django 3.0.7 on 2020-06-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200623_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('payment', models.CharField(max_length=50, verbose_name='Forma de Pagamento')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
